export const CartActionTypes={
    CART_ADDPRODUCT: "CART_ADDPRODUCT",
    CART_REMOVEPRODUCT: "CART_REMOVEPRODUCT",
    CART_SETID: "CART_SETID",
    CART_LOADPRODUCTS: "CART_LOADPRODUCTS",
    CART_CLEAR: "CART_CLEAR",
    CART_LOADCART_START: "CART_LOADCART_START",
    CART_LOADCART_FINISH: "CART_LOADCART_FINISH",
    CART_PRODUCTNOTFOUND: "CART_PRODUCTNOTFOUND",
}