export const CartActionTypes={
    CART_ADDPRODUCT: "CART_ADDPRODUCT",
    CART_REMOVEPRODUCT: "CART_REMOVEPRODUCT",
    CART_SETID: "CART_SETID",
    CART_LOADPRODUCTS: "CART_LOADPRODUCTS",
    CART_CLEAR: "CART_CLEAR",
}