export const ExamActionTypes= {
    FETCH_EXAMS_SUCCESS: "FETCH_EXAMS_SUCCESS",
    FETCH_EXAMS_FALIURE: "FETCH_EXAMS_FALIURE",
    FETCH_EXAMS_REQUEST: "FETCH_EXAMS_REQUEST", 
    CREATE_EXAM: "CREATE_EXAM",
    DELETE_EXAM: "DELETE_EXAM",
    TOGGLE_EXAMSTATUS: "TOGGLE_EXAMSTATUS",
    UPDATE_EXAM: "UPDATE_EXAM",
}