export const ExamActionTypes= {
    FETCH_EXAMS_SUCCESS: "FETCH_EXAMS_SUCCESS",
    FETCH_EXAMS_FALIURE: "FETCH_EXAMS_FALIURE",
    FETCH_EXAMS_REQUEST: "FETCH_EXAMS_REQUEST", 
    CREATE_EXAM: "CREATE_EXAM",
    DELETE_EXAM: "DELETE_EXAM",
    TOGGLE_EXAMSTATUS: "TOGGLE_EXAMSTATUS",
    UPDATE_EXAM_START: "UPDATE_EXAM_START",
    UPDATE_EXAM: "UPDATE_EXAM",
    UPDATE_EXAM_FAIL: "UPDATE_EXAM_FAIL",
    START_CREATING_EXAM: "START_CREATING_EXAM",
    FINISH_CREATING_EXAM: "FINISH_CREATING_EXAM",
    START_EDITING_EXAM: "START_EDITING_EXAM",
    FINISH_EDITING_EXAM: "FINISH_EDITING_EXAM",
    RESET: "RESET"
}