export const PracticeTestActionTypes={
    FETCH_PRACTICETESTS_REQUEST: "FETCH-PRACTICETESTS_REQUEST",
    SELECTED_PRACTICETEST: "SELECTED_PRACTICETEST",
    REMOVE_SELECTED_PRACTICETEST_EXAM: "REMOVE_SELECTED_PRACTICETEST_EXAM",
    TOGGLE_PRACTICETESTSTATUS: "TOGGLE_PRACTICETESTSTATUS",
    FETCH_PRACTICETESTS_SUCCESS: "FETCH_PRACTICETESTS_SUCCESS",
    FETCH_PRACTICETESTS_FALIURE: "FETCH_PRACTICETESTS_FALIURE",
    DELETE_PRACTICETEST: "DELETE_PRACTICETEST",
    CREATE_PRACTICETEST: "CREATE_PRACTICETEST",
    EDIT_PRACTICETEST: "EDIT_PRACTICETEST",
    FETCH_PRACTICETESTS_BYID: "FETCH_PRACTICETESTS_BYID",
    SELECTED_PRACTICETEST_ADDEXAM: "SELECTED_PRACTICETEST_ADDEXAM",
    SELECTED_PRACTICETEST_UPDATE: "SELECTED_PRACTICETEST_UPDATE",
    SELECTED_PRACTICETEST_ADDWSWP: "SELECTED_PRACTICETEST_ADDWSWP"

};